on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    if: github.ref == 'refs/heads/master'
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: use node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: build
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_USER: ${{ secrets.FTP_USER }}
      run: |
        echo "FTP_HOST=$FTP_HOST" > .env
        echo "FTP_PASSWORD=$FTP_PASSWORD" >> .env
        echo "FTP_USER=$FTP_USER" >> .env
        npm i
        CI=false npm run build
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_HOST }}
        ftp-username: ${{ secrets.FTP_USER }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: build/